name: Create Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build project
        run: npm run build
      
      - name: Create ZIP archive
        run: |
          zip -r personal-website-${{ github.ref_name }}.zip dist

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: personal-website-${{ github.ref_name }}.zip
          body: |
            ## Personal Website Release ${{ github.ref_name }}
            
            ### Changes in this release
            - See commit history for details
            
            ### Installation
            1. Download the ZIP file
            2. Extract to your web server
            3. Or run with Docker using the included Dockerfile
